# .travis.yml - Travis CI Configuration

language: node_js

node_js:
  - "6"

# Only create a new version on pushes to certain branches.
branches:
  only:
    - master

before_install:
  - npm install -g hexo

install:
  - npm install

# Notice: Replace 'YOUR NAME' and 'YOUR EMAIL'
before_script:
  - git config --global user.name 'HearingVietnam-bot'
  - git config --global user.email 'hearingvietnam-bot@gmail.com'

# Maybe add minification scripts here
script:
  - hexo generate

after_success:
  - source .travis/deploy.sh
